config/routes.rb
Mockshare::Application.routes.draw do
  resources :cards

  devise_for :users

  get 'about' => "pages#about"

  root :to => 'pages#home'

end

app/models/card.rb
class Card < ActiveRecord::Base
  attr_accessible :description

  validates :description, presence: true

  belongs_to :user
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, # :recoverable
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  has_many :cards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cards }
    end
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    @card = Card.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/new
  # GET /cards/new.json
  def new
    @card = current_user.cards.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/1/edit
  def edit
    @card = current_user.cards.find(params[:id])
    #Change refer to cards by the current user
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = current_user.cards.new(params[:card])

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render json: @card, status: :created, location: @card }
      else
        format.html { render action: "new" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cards/1
  # PUT /cards/1.json
  def update
    @card = current_user.cards.find(params[:id])

    respond_to do |format|
      if @card.update_attributes(params[:card])
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card = current_user.cards.find(params[:id])
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def action
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cards/_card.html.erb
<tr>
  <td><%= card.description %></td>
  <td><%= link_to 'Show', card %></td>
  <% if current_user == card.user %>
  <!-- Only show if logged in user created the card -->
    <td><%= link_to 'Edit', edit_card_path(card) %></td>
    <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</tr>

app/views/cards/_form.html.erb
<%= simple_form_for(@card, html: { class: "form-horizontal" }) do |f| %>
  <%= f.error_notification %>


    <%= f.input :description, as: :text, input_html: { rows: "3" } %>


  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<div class="well well-large">

  <h1>Editing card</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @card %> |
  <%= link_to 'Back', cards_path %>

</div>

app/views/cards/index.html.erb
<div class="well well-large">
  <h1>Listing cards</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Description</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
        <%= render @cards %>
    </tbody>
  </table>

  <br />

  <%= link_to 'New Card', new_card_path %>
</div>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<div class="row">
  <div class="span6 offset2">
    <div class="well">
      <p>
        <%= @card.description %>
      </p>
      <p>
        By: <%= @card.user.name %>
      </p>
      <% if current_user == @card.user %>
        <%= link_to 'Edit', edit_card_path(@card) %> |
      <% end %>
        <%= link_to 'Back', cards_path %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    Created by <%= link_to "Drew Butler", "http://www.butlerandrew.com" %>
  </small>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

		<%= link_to "Mockshare", root_path, class: "brand" %>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
        </ul>
        <ul class="nav pull-right">
		  	<% if user_signed_in? %>
			 <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
		    <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
			<% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
         <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title>Mockshare</title>
      <%= stylesheet_link_tag    "application", :media => "all" %>
      <%= javascript_include_tag "application" %>
      <%= csrf_meta_tags %>
    </head>
    <body>
      <%= render 'layouts/header' %>

      <div class="container">
        <% flash.each do |name, msg| %>
		  		<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
		  <% end %>
		  <%= yield %>

        <%= render 'layouts/footer' %>
      </div>

    </body>
  </html>

app/views/pages/about.html.erb
<div class="well well-large">
  <h1>About</h1>

  <p><%= link_to "Sign up Now!", new_user_registration_path, class: "btn btn-primary" %></p>
  <p>Mockshare is a web service to allow users to share their mockups of websites, mobile apps, and other mockups they want to share with the world.</p>
</div>

app/views/pages/home.html.erb
<% if user_signed_in? %>
	<div class="hero-unit">
	   <h1>Welcome back</h1>
	   <p>Got a picture to add?</p>
		 <p><%= link_to "Add a Mockup", new_user_registration_path, class: "btn btn-primary btn-large" %></a></p>
	</div>
<% else %>
	<div class="hero-unit">
  		<h1>Welcome to Mockshare</h1>
  		<p>Share your mockups with the world</p>
  		<p><%= link_to "Sign up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %></a></p>
	</div>
<% end %>